id = "markdown-snippets"
name = "Markdown Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Bobby Mannino <manninobobby@icloud.com>"]
description = "Markdown snippets for the Zed IDE. A collection of Markdown snippets to improve your documentation speed."
repository = "https://github.com/bobbymannino/markdown-snippets-for-zed"
snippets = "./snippets/markdown.json"
